"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type Language = "ro" | "ru" | "en";

const LanguageContext = createContext<{ language: Language; setLanguage: (language: Language) => void }>({ language: "ro", setLanguage: () => {} });
const originalTexts = new WeakMap<Text, string>();

const translations: Record<"en" | "ru", Record<string, string>> = {
  en: {
    // Panoul de consimțământ. Traducerea nu e cosmetică: un consimțământ pe care
    // vizitatorul nu îl înțelege nu este informat, deci nu este valabil.
    "Cookie-uri și confidențialitate": "Cookies and privacy",
    "Folosim cookie-uri strict necesare pentru funcționarea site-ului. Pentru statistici de utilizare și pentru măsurarea campaniilor avem nevoie de acordul tău. Poți refuza fără să pierzi nimic din site.": "We use strictly necessary cookies to run the site. For usage statistics and campaign measurement we need your consent. You can decline without losing anything on the site.",
    "Detalii în": "Details in the",
    "Politica de cookie-uri": "Cookie Policy",
    "Politica de confidențialitate": "Privacy Policy",
    "Accept toate": "Accept all",
    "Limba": "Language",
    "Refuz toate": "Decline all",
    "Setări": "Settings",
    "Ascunde setările": "Hide settings",
    "Strict necesare": "Strictly necessary",
    "Sesiune, preferința de limbă, securitate. Nu pot fi dezactivate.": "Session, language preference, security. These cannot be turned off.",
    "Statistici": "Statistics",
    "Cum e folosit site-ul, în formă agregată.": "How the site is used, in aggregate form.",
    "Măsurarea campaniilor prin Meta. Implică transfer în SUA.": "Campaign measurement through Meta. Involves a transfer to the USA.",
    "Salvează alegerea": "Save my choice",
    "Setări cookie-uri": "Cookie settings",
    "Confidențialitate": "Privacy",
    "Cookie-uri": "Cookies",
    "și": "and",
    "Produse": "Products", "Despre": "About", "Despre noi": "About us", "Ecosistem": "Ecosystem", "Clienți": "Customers", "Contact": "Contact", "Solicită demo": "Request a demo",
    "Suita software care crește odată cu afacerea ta": "The software suite that grows with your business",
    "Un singur": "One", "ecosistem.": "ecosystem.", "Toată afacerea ta.": "Your entire business.",
    "Sisteme specializate pentru service auto, contabilitate și construcții, cu module care lucrează împreună ca să vezi întreaga afacere dintr-o singură privire.": "Specialized systems for auto service, accounting and construction, with modules that work together to give you a complete view of your business.",
    "Solicită un demo": "Request a demo", "Descoperă produsele": "Explore products", "sisteme integrate": "integrated systems", "Suport": "Dedicated", "dedicat": "support",
    "Rapoarte în timp real": "Real-time reports", "Automatizări": "Automations", "API deschis": "Open API",
    "Service auto": "Auto Service", "Contabilitate": "Accounting", "Construcții": "Construction", "Fabrică": "Factory",
    "Fațadă": "Facade", "Electricitate": "Electrical", "Interior": "Interior", "Lucrări din beton": "Concrete Works",
    "Case modulare": "Modular houses", "Mobilă": "Furniture", "Ferestre": "Windows", "Panouri sandwich": "Sandwich panels", "Porți și garduri": "Gates & fences", "Bucătării la comandă": "Custom kitchens",
    "Sisteme specializate.": "Specialized systems.", "O singură sursă de adevăr.": "One source of truth.",
    "Fiecare produs e puternic singur. Împreună, elimină munca dublă, Excel-urile paralele și datele pierdute între departamente.": "Each product is powerful on its own. Together, they eliminate duplicate work, parallel spreadsheets and data lost between departments.",
    "Service-ul tău, pe pilot automat.": "Your workshop on autopilot.", "Contabilitate fără haos.": "Accounting without chaos.", "Șantierul, sub control.": "Your job site, under control.",
    "Producția la comandă, organizată cap-coadă.": "Custom production, organized end to end.", "Produs în dezvoltare": "Product in development", "Disponibil în curând": "Coming soon", "Vezi produsul": "View product",
    "În interiorul Zafirok": "Inside Zafirok", "Tot ce ai nevoie pentru a conduce": "Everything you need to run", "afacerea": "your business",
    "O platformă unică pentru clienți, operațiuni, documente și decizii — configurată după procesele industriei tale.": "One platform for customers, operations, documents and decisions — configured around your industry's workflows.",
    "Module operaționale": "Operational modules", "Construiește sistemul potrivit afacerii tale": "Build the right system for your business",
    "Fiecare modul se activează și se achită separat, dar folosește aceleași date și se conectează cu restul sistemului.": "Each module is activated and billed separately, while sharing the same data and connecting with the rest of the system.",
    "Vânzări": "Sales", "Achiziții": "Purchasing", "Stocuri": "Inventory", "Proiecte": "Projects", "Planificare": "Planning", "Documente": "Documents",
    "Istoric și vizibilitate": "History and visibility", "Securitate și control": "Security and control", "Flexibilitate și conectare": "Flexibility and connectivity",
    "Istoricul activității": "Activity history", "Cronologia clientului": "Customer timeline", "Jurnal de audit": "Audit log", "Istoricul versiunilor": "Version history", "Căutare globală": "Global search", "Rapoarte și analiză": "Reports & analytics",
    "Backup automat": "Automatic backups", "Permisiuni bazate pe roluri": "Role-based permissions", "Roluri pentru utilizatori": "User roles", "Controlul accesului": "User access control", "Notificări": "Notifications", "Administrare multi-companie": "Multi-company management",
    "Manager de fișiere": "File manager", "Atașamente": "File attachments", "Câmpuri personalizate": "Custom fields", "Integrări": "Integrations", "Multi-locație": "Multi-location", "Asistent AI": "AI assistant",
    "Cloud pe orice dispozitiv": "Cloud on any device", "Sincronizare în timp real": "Real-time synchronization", "Date pregătite pentru decizii": "Decision-ready data",
    "Alegi ce ai nevoie.": "Choose what you need.", "Extinzi când crești.": "Expand as you grow.", "Capabilități": "Capabilities",
    "Afaceri reale,": "Real businesses,", "rezultate reale": "real results", "CRM + ERP": "CRM + ERP", "Toată afacerea, într-un singur": "Your entire business, in one", "sistem": "system",
    "Relația cu clientul": "Customer relationships", "Resursele companiei": "Company resources", "Date conectate · Fluxuri specializate · O singură sursă de adevăr": "Connected data · Specialized workflows · One source of truth",
    "Pregătit să-ți vezi afacerea": "Ready to see your business", "dintr-o singură privire?": "at a glance?", "Programează un demo": "Schedule a demo", "Contactează-ne": "Contact us", "Companie": "Company",
    "Despre Zafirok": "About Zafirok", "Software pentru afaceri reale, construit de oameni care le": "Software for real businesses, built by people who", "înțeleg.": "understand them.",
    "Credem că afacerile mici și mijlocii merită sisteme moderne, fără implementări costisitoare, contracte complicate sau procese greu de înțeles.": "We believe small and medium businesses deserve modern systems without expensive implementations, complicated contracts or hard-to-understand processes.",
    "Misiunea noastră": "Our mission", "Mai puțin haos. Mai mult timp pentru creștere.": "Less chaos. More time to grow.",
    "Construim sisteme care ajută antreprenorii să organizeze clienții, echipele, documentele și operațiunile într-un singur mediu. Scopul nostru este simplu: mai puțină muncă administrativă, decizii mai clare și dezvoltare sustenabilă.": "We build systems that help entrepreneurs organize customers, teams, documents and operations in one environment. Our goal is simple: less administrative work, clearer decisions and sustainable growth.",
    "Viziunea noastră": "Our vision", "Tehnologie accesibilă, adaptată fiecărei industrii.": "Accessible technology, tailored to every industry.",
    "O platformă cloud colaborativă, modulară și ușor de folosit, care crește odată cu afacerea și se adaptează fluxurilor reale din fiecare nișă.": "A collaborative, modular and easy-to-use cloud platform that grows with the business and adapts to real workflows in every niche.",
    "Construit de CreateGo": "Built by CreateGo", "Produse software din 2009.": "Software products since 2009.",
    "Sisteme CRM și platforme ERP": "CRM systems and ERP platforms", "Automatizarea fluxurilor de lucru": "Workflow automation", "Aplicații cloud și sisteme de stocuri": "Cloud applications and inventory systems", "Platforme pentru gestiunea afacerii": "Business management platforms", "Soluții bazate pe inteligență artificială": "AI-powered solutions",
    "Cum lucrăm": "How we work", "Construim împreună cu antreprenorii.": "Built together with entrepreneurs.", "Ascultăm proprietarii și echipele, înțelegem provocările operaționale și prioritizăm funcțiile după nevoi reale, nu după presupuneri.": "We listen to owners and teams, understand operational challenges and prioritize features based on real needs, not assumptions.",
    "Simplitate practică": "Practical simplicity", "Transparență și încredere": "Transparency and trust", "Suport uman": "Human support", "Evoluție continuă": "Continuous improvement",
    "Software-ul puternic nu trebuie să fie complicat. Construim instrumente pe care echipele le pot înțelege și folosi rapid.": "Powerful software does not have to be complicated. We build tools that teams can understand and use quickly.", "Prețuri clare, date care îți aparțin și relații construite prin comunicare onestă și practici corecte.": "Clear pricing, data that belongs to you and relationships built through honest communication and fair practices.", "Ajutor rapid și aplicat, oferit de oameni care înțeleg atât produsul, cât și realitatea operațională a afacerii.": "Fast, practical help from people who understand both the product and the operational reality of your business.", "Îmbunătățim platforma pornind de la probleme reale și o dezvoltăm odată cu afacerile clienților noștri.": "We improve the platform around real problems and develop it alongside our customers' businesses.",
    "dezvoltă sisteme practice, scalabile și ușor de folosit pentru medii operaționale reale. Zafirok reunește această experiență într-un ecosistem modern pentru gestiunea afacerii.": "builds practical, scalable and easy-to-use systems for real operational environments. Zafirok brings this experience together in a modern business management ecosystem.",
    "Hai să discutăm despre": "Let's talk about", "afacerea ta.": "your business.", "Ai nevoie de suport, vrei o demonstrație sau cauți sistemul potrivit pentru echipa ta? Suntem aici să te ajutăm.": "Need support, want a demo or are looking for the right system for your team? We are here to help.",
    "Europa": "Europe", "SUA și Canada": "US & Canada", "Suport și întrebări generale": "Support and general inquiries", "Apeluri și WhatsApp": "Calls and WhatsApp", "Răspundem cât mai rapid": "We respond as quickly as possible", "Echipa noastră îți oferă ajutor practic și direct.": "Our team provides practical, direct help.", "Trimite un email": "Send an email",
    // Produse, ecosistem, testimoniale, subsol și paginile juridice (septembrie 2026).
    "Devize, etape de proiect, pontaj și costuri reale pe fiecare lucrare — vizibile în timp real, de oriunde.": "Estimates, project stages, timesheets and actual costs on every job — visible in real time, from anywhere.",
    "Devize și situații de lucrări": "Estimates and work statements",
    "Pontaj echipe & utilaje": "Crew & equipment timesheets",
    "Costuri reale pe proiect": "Actual costs per project",
    "Fabrica ta, sub control.": "Your factory, under control.",
    "CRM și ERP pentru fabrici de case modulare, mobilă, ferestre, panouri sandwich, porți, garduri și bucătării la comandă.": "CRM and ERP for manufacturers of modular houses, furniture, windows, sandwich panels, gates, fences and custom kitchens.",
    "Comenzi și clienți într-un singur loc": "Orders and customers in one place",
    "Planificarea producției": "Production planning",
    "Costuri și progres în timp real": "Real-time costs and progress",
    "De la programare la deviz și predarea mașinii — tot fluxul service-ului auto, digitalizat cap-coadă.": "From booking to estimate and vehicle handover — the whole auto service workflow, digital end to end.",
    "Programări & recepție rapidă": "Appointments & fast check-in",
    "Devize și comenzi de piese": "Estimates and parts orders",
    "Istoric complet pe vehicul": "Full vehicle history",
    "În curând": "Coming soon",
    "Facturare, e-Factura și rapoarte fiscale într-un sistem care închide luna fără nopți pierdute.": "Invoicing, e-Factura and tax reports in a system that closes the month without sleepless nights.",
    "Facturare & e-Factura": "Invoicing & e-Factura",
    "Registre și jurnale automate": "Automatic ledgers and journals",
    "Rapoarte fiscale la zi": "Up-to-date tax reports",
    "Zafirok este construit modular: activezi doar funcțiile de care are nevoie afacerea ta și plătești separat pentru fiecare modul. Când adaugi un modul nou, acesta se conectează instant cu datele și procesele pe care le folosești deja.": "Zafirok is built in modules: you switch on only the features your business needs and pay separately for each module. When you add a new module, it connects instantly to the data and processes you already use.",
    "Date sincronizate": "Synchronised data",
    "Clientul din CRM e același din facturare. Fără copy-paste, fără versiuni diferite ale adevărului.": "The customer in the CRM is the same one in invoicing. No copy-paste, no different versions of the truth.",
    "Cloud & mobil": "Cloud & mobile",
    "Lucrezi din birou, din service sau de pe șantier. Datele te urmează pe orice dispozitiv.": "Work from the office, the workshop or the building site. Your data follows you on any device.",
    "Securitate serioasă": "Serious security",
    "Backup automat, acces pe roluri și criptare. Datele afacerii tale rămân doar ale tale.": "Automatic backups, role-based access and encryption. Your business data stays yours alone.",
    "Implementare rapidă": "Fast implementation",
    "Pornești în zile, nu în luni. Importăm datele existente și îți instruim echipa.": "Get started in days, not months. We import your existing data and train your team.",
    "Cash flow, vânzări, costuri pe proiect — cifrele care contează, fără să aștepți sfârșitul lunii.": "Cash flow, sales, costs per project — the numbers that matter, without waiting for month end.",
    "Suport care răspunde": "Support that answers",
    "Oameni reali, care înțeleg afacerea ta, nu doar software-ul. În limba ta, când ai nevoie.": "Real people who understand your business, not just the software. In your language, when you need it.",
    "companii active": "active companies",
    "uptime garantat": "guaranteed uptime",
    "documente procesate": "documents processed",
    "Acum, datorită CRM-ului pentru electricieni și renovări, pot să țin sub control lucrul echipei mele: pe cine plătesc, ce volum face fiecare zilnic și orele de muncă. Înainte țineam totul în minte și aveam un carnețel în care era mereu încurcătură. Trebuia să calculez constant, era greu să țin cont de detaliile mici și nu mai știam cât câștig cu adevărat de pe fiecare obiect. Acum înregistrez toate proiectele în CRM și este atât de ușor să țin evidența, chiar e o plăcere. La început lucram în soft de pe telefon, dar apoi am trecut pe tabletă — îmi place să văd cifrele mai mari. Recomand: este mai simplu decât să ții calculele pe foaie și îți ia mai puțin timp decât să notezi în caiet.": "Now, thanks to the CRM for electricians and renovations, I can keep my team's work under control: who I pay, how much each person gets done every day and the hours worked. Before, I kept everything in my head and had a notebook that was always a mess. I had to calculate constantly, it was hard to keep track of the small details and I no longer knew how much I really earned on each job. Now I record every project in the CRM and keeping track is so easy it's actually a pleasure. At first I used the software on my phone, but then I switched to a tablet — I like seeing the numbers bigger. I recommend it: it's simpler than doing the maths on paper and takes less time than writing things down in a notebook.",
    "Electricitate și renovări": "Electrical work and renovations",
    "Căutam un CRM pentru service auto și, când am văzut publicitatea Zafirok, mi-a plăcut ce am văzut. Am scris un simplu comentariu că sunt interesată și nu credeam că o să revină cineva. Dar echipa a fost foarte receptivă atât la început, cât și ulterior. Le-am sugerat câteva îmbunătățiri și le-au implementat foarte rapid. Este un sistem digital modern pentru service auto.": "I was looking for a CRM for an auto service, and when I saw the Zafirok ad I liked what I saw. I left a simple comment saying I was interested and didn't think anyone would get back to me. But the team was very responsive, both at the start and afterwards. I suggested a few improvements and they implemented them very quickly. It's a modern digital system for auto services.",
    "Un prieten care folosește deja Zafirok drept CRM pentru service-ul lui auto ne-a recomandat să ne înregistrăm. După doar câteva minute de utilizare, am înțeles că este ceea ce avem nevoie. Având câteva filiale, s-a dovedit a fi cea mai bună soluție. Este ușor de folosit, iar totul este gândit exact pentru nevoile pe care le avem într-un service auto.": "A friend who already uses Zafirok as the CRM for his auto service recommended that we sign up. After just a few minutes of use, we understood it was what we needed. With several branches, it turned out to be the best solution. It's easy to use, and everything is designed exactly for the needs we have in an auto service.",
    "CRM-ul gestionează relația cu clientul. ERP-ul organizează resursele și operațiunile companiei. Zafirok le conectează prin module independente, pe care le activezi în funcție de nevoile și etapa afacerii tale.": "The CRM manages the customer relationship. The ERP organises the company's resources and operations. Zafirok connects them through independent modules that you switch on according to your business's needs and stage.",
    "Nu adaptăm afacerea la un software generic. Construim fluxurile în jurul modului în care lucrează fiecare nișă.": "We don't bend your business to fit generic software. We build the workflows around the way each niche works.",
    "Centralizează clienții, vânzările, comunicarea și istoricul fiecărei relații.": "Brings together customers, sales, communication and the history of every relationship.",
    "Coordonează operațiunile, costurile, stocurile, echipele și fluxurile financiare.": "Coordinates operations, costs, stock, teams and financial flows.",
    "Pontaj": "Timesheets",
    "Devize": "Estimates",
    "Facturare": "Invoicing",
    "Rapoarte": "Reports",
    "Programează un demo de 30 de minute. Îți arătăm ecosistemul pe datele tale, nu pe slide-uri.": "Book a 30-minute demo. We'll show you the ecosystem on your own data, not on slides.",
    "Demo gratuit · Fără obligații · Răspundem în aceeași zi": "Free demo · No obligation · Same-day reply",
    "Ecosistem de sisteme software pentru afaceri: CRM, service auto, contabilitate, construcții și fabrici. Un singur partener, toată afacerea acoperită.": "An ecosystem of business software: CRM, auto service, accounting, construction and manufacturing. One partner, your whole business covered.",
    "© 2026 Zafirok. Toate drepturile rezervate.": "© 2026 Zafirok. All rights reserved.",
    "Marketing": "Marketing",
    "Ce date colectăm și de ce": "What data we collect and why",
    "Această pagină se referă la site-ul de prezentare zafirok.com. Aplicațiile Zafirok au fiecare propria politică, fiindcă acolo datele sunt ale clienților noștri, nu ale noastre.": "This page covers the zafirok.com presentation website. Each Zafirok application has its own policy, because the data there belongs to our customers, not to us.",
    "Ultima actualizare:": "Last updated:",
    "19 august 2026": "19 August 2026",
    "Cine răspunde pentru datele tale": "Who is responsible for your data",
    "Operatorul este": "The controller is",
    ", IDNO": ", IDNO",
    ", cu sediul în str. Calea Ieșilor 16, nr. 3, ap. 8V, MD-2069, Chișinău, Republica Moldova.": ", registered at str. Calea Ieșilor 16, nr. 3, ap. 8V, MD-2069, Chișinău, Republic of Moldova.",
    "este marca sub care oferim aplicațiile descrise pe acest site.": "is the brand under which we offer the applications described on this website.",
    "Plățile pentru abonamente sunt facturate de": "Subscription payments are invoiced by",
    ", 7901 4th St N, STE 300, St. Petersburg, FL 33702, Statele Unite, care prelucrează în acest scop numele, adresa de email și datele de facturare. Pentru orice altceva legat de datele tale, operatorul rămâne CreativMaro SRL.": ", 7901 4th St N, STE 300, St. Petersburg, FL 33702, United States, which processes your name, email address and billing details for this purpose. For anything else related to your data, the controller remains CreativMaro SRL.",
    "Pentru orice întrebare privind datele tale sau pentru exercitarea drepturilor de mai jos, scrie la": "For any question about your data or to exercise the rights below, write to",
    ". Răspundem în cel mult o lună de la primirea cererii.": ". We reply within one month of receiving your request at the latest.",
    "Prelucrăm datele conform": "We process data in accordance with",
    "Legii nr. 195/2024 privind protecția datelor cu caracter personal": "Law No. 195/2024 on the protection of personal data",
    ", aplicabilă din 23 august 2026, iar pentru vizitatorii din Spațiul Economic European și conform Regulamentului (UE) 2016/679.": ", applicable from 23 August 2026, and, for visitors from the European Economic Area, also with Regulation (EU) 2016/679.",
    "Ce colectăm, în ce scop și pe ce temei": "What we collect, for what purpose and on what basis",
    "Pe site-ul de prezentare nu ai cont și nu îți cerem date pentru a naviga. Colectăm strict următoarele:": "You have no account on the presentation website and we don't ask for any data to browse it. We collect strictly the following:",
    "Date": "Data",
    "Scop": "Purpose",
    "Temei juridic": "Legal basis",
    "Păstrare": "Retention",
    "Adresa IP, tipul browserului, pagina vizitată": "IP address, browser type, page visited",
    "Funcționarea site-ului, securitate, prevenirea abuzurilor": "Running the website, security, abuse prevention",
    "Interes legitim,": "Legitimate interest,",
    "art. 6 alin. (1) lit. f)": "Article 6(1)(f)",
    "Maximum 90 de zile în jurnalele tehnice": "Up to 90 days in technical logs",
    "Preferința de limbă": "Language preference",
    "Afișarea site-ului în limba aleasă": "Showing the website in the chosen language",
    "Strict necesar pentru serviciul cerut": "Strictly necessary for the requested service",
    "Până la ștergerea din browser": "Until deleted from the browser",
    "Statistici agregate de utilizare": "Aggregated usage statistics",
    "Înțelegerea modului în care e folosit site-ul": "Understanding how the website is used",
    "Consimțământ,": "Consent,",
    "art. 6 alin. (1) lit. a)": "Article 6(1)(a)",
    "Doar dacă accepți, maximum 14 luni": "Only if you accept, up to 14 months",
    "Identificatori publicitari Meta": "Meta advertising identifiers",
    "Măsurarea campaniilor de promovare": "Measuring advertising campaigns",
    "Doar dacă accepți, conform politicii Meta": "Only if you accept, under Meta's policy",
    "Numele și adresa de email, dacă ne scrii": "Name and email address, if you write to us",
    "Răspunsul la mesajul tău": "Replying to your message",
    "Măsuri precontractuale,": "Pre-contractual measures,",
    "art. 6 alin. (1) lit. b)": "Article 6(1)(b)",
    "24 de luni de la ultima corespondență": "24 months from the last correspondence",
    "Statisticile și identificatorii publicitari nu pornesc înainte să alegi. Dacă refuzi, site-ul funcționează identic.": "Statistics and advertising identifiers do not start before you choose. If you decline, the website works exactly the same.",
    "Cui ajung datele": "Who receives the data",
    "Nu vindem date și nu le facem publice. Le pot prelucra doar furnizorii de care avem nevoie ca să ținem site-ul în funcțiune:": "We don't sell data and we don't make it public. It may be processed only by the providers we need to keep the website running:",
    ", Statele Unite, găzduire și jurnale de acces.": ", United States, hosting and access logs.",
    ", Statele Unite, măsurarea campaniilor, numai cu acordul tău.": ", United States, campaign measurement, only with your consent.",
    "Putem transmite date și autorităților, dar numai când o obligație legală ne impune asta și numai în limita cerută.": "We may also disclose data to public authorities, but only when a legal obligation requires it and only to the extent required.",
    "Transferuri în afara Republicii Moldova": "Transfers outside the Republic of Moldova",
    "Furnizorii de mai sus prelucrează date în Statele Unite. Transferul se face în baza": "The providers above process data in the United States. The transfer is based on",
    "clauzelor contractuale standard": "standard contractual clauses",
    ", mecanism admis fără autorizare prealabilă de": ", a mechanism permitted without prior authorisation by",
    "art. 46 alin. (2) lit. c)": "Article 46(2)(c)",
    "din Legea nr. 195/2024, iar pentru identificatorii publicitari și în baza consimțământului tău explicit,": "of Law No. 195/2024, and, for advertising identifiers, also on the basis of your explicit consent,",
    "art. 49 alin. (1) lit. a)": "Article 49(1)(a)",
    "Documentele și fișierele încărcate în aplicațiile noastre sunt stocate pe servere din": "Documents and files uploaded to our applications are stored on servers in",
    "Franța": "France",
    ". Fiind în Spațiul Economic European, aceste transferuri nu necesită nicio formalitate suplimentară, conform": ". As France is in the European Economic Area, these transfers require no further formality, under",
    "art. 44 alin. (2)": "Article 44(2)",
    "Poți cere oricând o copie a garanțiilor aplicate, scriindu-ne la adresa de mai sus.": "You can ask at any time for a copy of the safeguards applied by writing to us at the address above.",
    "Drepturile tale": "Your rights",
    "Ai, în legătură cu datele tale, următoarele drepturi:": "In relation to your data, you have the following rights:",
    "Acces": "Access",
    ", să afli ce date avem despre tine, art. 15.": ", to find out what data we hold about you, Article 15.",
    "Rectificare": "Rectification",
    ", să corectăm ce e greșit, art. 16.": ", to have us correct anything that is wrong, Article 16.",
    "Ștergere": "Erasure",
    ", să eliminăm datele, art. 17.": ", to have us delete the data, Article 17.",
    "Restricționare": "Restriction",
    ", să oprim temporar prelucrarea, art. 18.": ", to have us temporarily stop processing, Article 18.",
    "Portabilitate": "Portability",
    ", să primești datele într-un format citibil automat, art. 20.": ", to receive the data in a machine-readable format, Article 20.",
    "Opoziție": "Objection",
    ", să te opui prelucrării întemeiate pe interes legitim, art. 21.": ", to object to processing based on legitimate interest, Article 21.",
    "Retragerea consimțământului": "Withdrawal of consent",
    ", oricând și la fel de simplu cum l-ai dat, art. 7 alin. (3). Pentru cookie-uri, folosește „Setări cookie-uri\" din piciorul paginii.": ", at any time and as easily as you gave it, Article 7(3). For cookies, use \"Cookie settings\" in the page footer.",
    "Nu luăm decizii automatizate cu efecte juridice asupra ta și nu facem profilare pe site-ul de prezentare.": "We make no automated decisions with legal effects on you and do no profiling on the presentation website.",
    "Dacă nu ești mulțumit de răspunsul nostru": "If you are not satisfied with our reply",
    "Scrie-ne întâi nouă, de obicei se rezolvă mai repede. Dacă nu ești mulțumit, ai dreptul să depui plângere la": "Write to us first; it is usually resolved faster. If you are not satisfied, you have the right to lodge a complaint with the",
    "Centrul Național pentru Protecția Datelor cu Caracter Personal": "National Centre for Personal Data Protection",
    ", str. Serghei Lazo 48, Chișinău, MD-2004, sau prin": ", str. Serghei Lazo 48, Chișinău, MD-2004, or via",
    ". Te poți adresa și instanței de judecată.": ". You may also go to court.",
    "Modificări": "Changes",
    "Când schimbăm ceva important, actualizăm data de sus și, dacă modificarea te afectează direct, îți cerem din nou alegerea privind cookie-urile. Versiunile anterioare sunt disponibile la cerere.": "When we change something important, we update the date at the top and, if the change affects you directly, we ask for your cookie choice again. Previous versions are available on request.",
    "Ce se salvează în browserul tău": "What is stored in your browser",
    "Site-ul funcționează complet și dacă refuzi tot ce nu e strict necesar. Nu ascundem opțiunea de refuz și nu îți cerem alegerea din nou la fiecare vizită.": "The website works fully even if you decline everything that isn't strictly necessary. We don't hide the option to decline and we don't ask for your choice again on every visit.",
    "Alegerea ta, oricând": "Your choice, at any time",
    "Îți poți schimba opțiunile în orice moment, fără să ne scrii și fără să îți creezi cont. Retragerea are efect imediat pentru vizitele următoare.": "You can change your options at any moment, without writing to us and without creating an account. Withdrawal takes effect immediately for your next visits.",
    "Fără ele site-ul nu poate funcționa, așa că nu îți cerem acordul pentru ele. Nu te urmăresc și nu ajung la nimeni altcineva.": "The website can't work without them, so we don't ask for your consent to them. They don't track you and they don't reach anyone else.",
    "Ce salvăm": "What we store",
    "La ce folosește": "What it is for",
    "Cât stă": "How long it stays",
    "limbă": "language",
    "Ține minte dacă citești în română, rusă sau engleză": "Remembers whether you read in Romanian, Russian or English",
    "Până îl ștergi": "Until you delete it",
    "Reține chiar alegerea ta privind cookie-urile, ca să nu te întrebăm iar": "Stores your cookie choice itself, so we don't ask you again",
    "12 luni": "12 months",
    "Ne arată ce pagini sunt citite și unde oamenii se opresc, în formă agregată. Pornesc numai dacă le accepți.": "They show us which pages are read and where people stop, in aggregated form. They start only if you accept them.",
    "În acest moment nu rulăm niciun instrument de statistică pe site-ul de prezentare. Dacă adăugăm unul, actualizăm această pagină și îți cerem din nou alegerea, înainte ca instrumentul să pornească.": "At the moment we run no statistics tool on the presentation website. If we add one, we will update this page and ask for your choice again before the tool starts.",
    "Pornesc numai cu acordul tău explicit și pot fi oprite oricând.": "They start only with your explicit consent and can be switched off at any time.",
    "Furnizor": "Provider",
    "Ce face": "What it does",
    "Unde ajung datele": "Where the data goes",
    "Măsoară câți vizitatori vin din campaniile noastre de promovare și ne ajută să nu arătăm reclame celor care ne-au contactat deja": "Measures how many visitors come from our advertising campaigns and helps us avoid showing ads to people who have already contacted us",
    "Meta Platforms Inc., Statele Unite": "Meta Platforms Inc., United States",
    "Pixelul transmite adresa IP și identificatori de dispozitiv către Meta, în Statele Unite. De aceea îl tratăm ca transfer internațional și îl pornim doar pe baza consimțământului explicit, conform": "The Pixel sends your IP address and device identifiers to Meta, in the United States. That is why we treat it as an international transfer and start it only on the basis of explicit consent, under",
    "din Legea nr. 195/2024. Detalii în": "of Law No. 195/2024. Details in the",
    "Cum le ștergi din browser": "How to delete them from your browser",
    "Pe lângă panoul nostru de setări, poți șterge sau bloca tot ce salvează site-urile direct din browser, de obicei din secțiunea de confidențialitate. Reține că blocarea totală afectează multe site-uri, nu doar pe al nostru.": "Besides our settings panel, you can delete or block everything websites store directly from your browser, usually in its privacy section. Keep in mind that blocking everything affects many websites, not just ours.",
  },
  ru: {
    "Cookie-uri și confidențialitate": "Файлы cookie и конфиденциальность",
    "Folosim cookie-uri strict necesare pentru funcționarea site-ului. Pentru statistici de utilizare și pentru măsurarea campaniilor avem nevoie de acordul tău. Poți refuza fără să pierzi nimic din site.": "Мы используем строго необходимые файлы cookie для работы сайта. Для статистики использования и оценки кампаний нам нужно ваше согласие. Вы можете отказаться, ничего не потеряв на сайте.",
    "Detalii în": "Подробнее в",
    "Politica de cookie-uri": "Политике использования cookie",
    "Politica de confidențialitate": "Политике конфиденциальности",
    "Accept toate": "Принять все",
    "Limba": "Язык",
    "Refuz toate": "Отклонить все",
    "Setări": "Настройки",
    "Ascunde setările": "Скрыть настройки",
    "Strict necesare": "Строго необходимые",
    "Sesiune, preferința de limbă, securitate. Nu pot fi dezactivate.": "Сессия, выбор языка, безопасность. Их нельзя отключить.",
    "Statistici": "Статистика",
    "Cum e folosit site-ul, în formă agregată.": "Как используется сайт, в агрегированном виде.",
    "Măsurarea campaniilor prin Meta. Implică transfer în SUA.": "Оценка кампаний через Meta. Предполагает передачу данных в США.",
    "Salvează alegerea": "Сохранить выбор",
    "Setări cookie-uri": "Настройки cookie",
    "Confidențialitate": "Конфиденциальность",
    "Cookie-uri": "Файлы cookie",
    "Marketing": "Маркетинг",
    "și": "и",
    "Produse": "Продукты", "Despre": "О нас", "Despre noi": "О нас", "Ecosistem": "Экосистема", "Clienți": "Клиенты", "Contact": "Контакты", "Solicită demo": "Запросить демо",
    "Suita software care crește odată cu afacerea ta": "Программная платформа, которая растёт вместе с бизнесом",
    "Un singur": "Единая", "ecosistem.": "экосистема.", "Toată afacerea ta.": "Весь ваш бизнес.",
    "Sisteme specializate pentru service auto, contabilitate și construcții, cu module care lucrează împreună ca să vezi întreaga afacere dintr-o singură privire.": "Специализированные системы для автосервиса, бухгалтерии и строительства с модулями, которые дают полную картину бизнеса.",
    "Solicită un demo": "Запросить демо", "Descoperă produsele": "Смотреть продукты", "sisteme integrate": "интегрированные системы", "Suport": "Поддержка", "dedicat": "специалистов",
    "Rapoarte în timp real": "Отчёты в реальном времени", "Automatizări": "Автоматизации", "API deschis": "Открытый API",
    "Service auto": "Автосервис", "Contabilitate": "Бухгалтерия", "Construcții": "Строительство", "Fabrică": "Производство",
    "Fațadă": "Фасад", "Electricitate": "Электрика", "Interior": "Интерьер", "Lucrări din beton": "Бетонные работы",
    "Case modulare": "Модульные дома", "Mobilă": "Мебель", "Ferestre": "Окна", "Panouri sandwich": "Сэндвич-панели", "Porți și garduri": "Ворота и заборы", "Bucătării la comandă": "Кухни на заказ",
    "Sisteme specializate.": "Специализированные системы.", "O singură sursă de adevăr.": "Единый источник данных.",
    "Fiecare produs e puternic singur. Împreună, elimină munca dublă, Excel-urile paralele și datele pierdute între departamente.": "Каждый продукт эффективен сам по себе. Вместе они устраняют дублирование работы, разрозненные таблицы и потерю данных.",
    "Service-ul tău, pe pilot automat.": "Ваш автосервис на автопилоте.", "Contabilitate fără haos.": "Бухгалтерия без хаоса.", "Șantierul, sub control.": "Стройка под контролем.",
    "Producția la comandă, organizată cap-coadă.": "Заказное производство от начала до конца.", "Produs în dezvoltare": "Продукт в разработке", "Disponibil în curând": "Скоро", "Vezi produsul": "Открыть продукт",
    "În interiorul Zafirok": "Внутри Zafirok", "Tot ce ai nevoie pentru a conduce": "Всё для управления", "afacerea": "бизнесом",
    "O platformă unică pentru clienți, operațiuni, documente și decizii — configurată după procesele industriei tale.": "Единая платформа для клиентов, операций, документов и решений, настроенная под процессы вашей отрасли.",
    "Module operaționale": "Операционные модули", "Construiește sistemul potrivit afacerii tale": "Создайте систему под свой бизнес",
    "Fiecare modul se activează și se achită separat, dar folosește aceleași date și se conectează cu restul sistemului.": "Каждый модуль подключается и оплачивается отдельно, но использует общие данные и связан с остальной системой.",
    "Vânzări": "Продажи", "Achiziții": "Закупки", "Stocuri": "Склад", "Proiecte": "Проекты", "Planificare": "Планирование", "Documente": "Документы",
    "Istoric și vizibilitate": "История и прозрачность", "Securitate și control": "Безопасность и контроль", "Flexibilitate și conectare": "Гибкость и интеграции",
    "Istoricul activității": "История действий", "Cronologia clientului": "Хронология клиента", "Jurnal de audit": "Журнал аудита", "Istoricul versiunilor": "История версий", "Căutare globală": "Глобальный поиск", "Rapoarte și analiză": "Отчёты и аналитика",
    "Backup automat": "Автоматические резервные копии", "Permisiuni bazate pe roluri": "Ролевые разрешения", "Roluri pentru utilizatori": "Роли пользователей", "Controlul accesului": "Контроль доступа", "Notificări": "Уведомления", "Administrare multi-companie": "Несколько компаний",
    "Manager de fișiere": "Файловый менеджер", "Atașamente": "Вложения", "Câmpuri personalizate": "Настраиваемые поля", "Integrări": "Интеграции", "Multi-locație": "Несколько локаций", "Asistent AI": "AI-ассистент",
    "Cloud pe orice dispozitiv": "Облако на любом устройстве", "Sincronizare în timp real": "Синхронизация в реальном времени", "Date pregătite pentru decizii": "Данные для принятия решений",
    "Alegi ce ai nevoie.": "Выбирайте нужное.", "Extinzi când crești.": "Расширяйте по мере роста.", "Capabilități": "Возможности",
    "Afaceri reale,": "Реальный бизнес,", "rezultate reale": "реальные результаты", "Toată afacerea, într-un singur": "Весь бизнес в единой", "sistem": "системе",
    "Relația cu clientul": "Работа с клиентами", "Resursele companiei": "Ресурсы компании", "Date conectate · Fluxuri specializate · O singură sursă de adevăr": "Связанные данные · Отраслевые процессы · Единый источник данных",
    "Pregătit să-ți vezi afacerea": "Готовы увидеть бизнес", "dintr-o singură privire?": "целиком?", "Programează un demo": "Запланировать демо", "Contactează-ne": "Связаться", "Companie": "Компания",
    "Despre Zafirok": "О Zafirok", "Software pentru afaceri reale, construit de oameni care le": "Программы для реального бизнеса от людей, которые его", "înțeleg.": "понимают.",
    "Credem că afacerile mici și mijlocii merită sisteme moderne, fără implementări costisitoare, contracte complicate sau procese greu de înțeles.": "Мы считаем, что малый и средний бизнес заслуживает современных систем без дорогого внедрения, сложных контрактов и непонятных процессов.",
    "Misiunea noastră": "Наша миссия", "Mai puțin haos. Mai mult timp pentru creștere.": "Меньше хаоса. Больше времени для роста.",
    "Construim sisteme care ajută antreprenorii să organizeze clienții, echipele, documentele și operațiunile într-un singur mediu. Scopul nostru este simplu: mai puțină muncă administrativă, decizii mai clare și dezvoltare sustenabilă.": "Мы создаём системы, которые объединяют клиентов, команды, документы и операции. Наша цель проста: меньше административной работы, более ясные решения и устойчивый рост.",
    "Viziunea noastră": "Наше видение", "Tehnologie accesibilă, adaptată fiecărei industrii.": "Доступные технологии для каждой отрасли.",
    "O platformă cloud colaborativă, modulară și ușor de folosit, care crește odată cu afacerea și se adaptează fluxurilor reale din fiecare nișă.": "Совместная, модульная и удобная облачная платформа, которая растёт вместе с бизнесом и адаптируется к реальным процессам каждой ниши.",
    "Construit de CreateGo": "Создано CreateGo", "Produse software din 2009.": "Программные продукты с 2009 года.",
    "Sisteme CRM și platforme ERP": "CRM-системы и ERP-платформы", "Automatizarea fluxurilor de lucru": "Автоматизация рабочих процессов", "Aplicații cloud și sisteme de stocuri": "Облачные приложения и складские системы", "Platforme pentru gestiunea afacerii": "Платформы управления бизнесом", "Soluții bazate pe inteligență artificială": "Решения на базе искусственного интеллекта",
    "Cum lucrăm": "Как мы работаем", "Construim împreună cu antreprenorii.": "Создаём вместе с предпринимателями.", "Ascultăm proprietarii și echipele, înțelegem provocările operaționale și prioritizăm funcțiile după nevoi reale, nu după presupuneri.": "Мы слушаем владельцев и команды, изучаем рабочие задачи и выбираем функции на основе реальных потребностей.",
    "Simplitate practică": "Практичная простота", "Transparență și încredere": "Прозрачность и доверие", "Suport uman": "Поддержка людей", "Evoluție continuă": "Постоянное развитие",
    "Software-ul puternic nu trebuie să fie complicat. Construim instrumente pe care echipele le pot înțelege și folosi rapid.": "Мощное программное обеспечение не должно быть сложным. Мы создаём инструменты, которые команды быстро понимают и осваивают.", "Prețuri clare, date care îți aparțin și relații construite prin comunicare onestă și practici corecte.": "Понятные цены, ваши собственные данные и отношения, основанные на честной коммуникации и справедливых принципах.", "Ajutor rapid și aplicat, oferit de oameni care înțeleg atât produsul, cât și realitatea operațională a afacerii.": "Быстрая практическая помощь от людей, которые понимают продукт и реальные процессы бизнеса.", "Îmbunătățim platforma pornind de la probleme reale și o dezvoltăm odată cu afacerile clienților noștri.": "Мы улучшаем платформу на основе реальных задач и развиваем её вместе с бизнесом наших клиентов.",
    "dezvoltă sisteme practice, scalabile și ușor de folosit pentru medii operaționale reale. Zafirok reunește această experiență într-un ecosistem modern pentru gestiunea afacerii.": "создаёт практичные, масштабируемые и удобные системы для реальных рабочих процессов. Zafirok объединяет этот опыт в современной экосистеме управления бизнесом.",
    "Hai să discutăm despre": "Давайте поговорим о", "afacerea ta.": "вашем бизнесе.", "Ai nevoie de suport, vrei o demonstrație sau cauți sistemul potrivit pentru echipa ta? Suntem aici să te ajutăm.": "Нужна поддержка, демонстрация или подходящая система для вашей команды? Мы готовы помочь.",
    "Europa": "Европа", "SUA și Canada": "США и Канада", "Suport și întrebări generale": "Поддержка и общие вопросы", "Apeluri și WhatsApp": "Звонки и WhatsApp", "Răspundem cât mai rapid": "Отвечаем максимально быстро", "Echipa noastră îți oferă ajutor practic și direct.": "Наша команда предоставит практическую помощь.", "Trimite un email": "Отправить email",
    // Produse, ecosistem, testimoniale, subsol și paginile juridice (septembrie 2026).
    "Devize, etape de proiect, pontaj și costuri reale pe fiecare lucrare — vizibile în timp real, de oriunde.": "Сметы, этапы проекта, табель и реальные затраты по каждому объекту — в реальном времени, из любой точки.",
    "Devize și situații de lucrări": "Сметы и акты выполненных работ",
    "Pontaj echipe & utilaje": "Табель бригад и техники",
    "Costuri reale pe proiect": "Реальные затраты по проекту",
    "Fabrica ta, sub control.": "Ваша фабрика под контролем.",
    "CRM și ERP pentru fabrici de case modulare, mobilă, ferestre, panouri sandwich, porți, garduri și bucătării la comandă.": "CRM и ERP для производителей модульных домов, мебели, окон, сэндвич-панелей, ворот, заборов и кухонь на заказ.",
    "Comenzi și clienți într-un singur loc": "Заказы и клиенты в одном месте",
    "Planificarea producției": "Планирование производства",
    "Costuri și progres în timp real": "Затраты и прогресс в реальном времени",
    "De la programare la deviz și predarea mașinii — tot fluxul service-ului auto, digitalizat cap-coadă.": "От записи до сметы и выдачи автомобиля — весь процесс автосервиса в цифре, от начала до конца.",
    "Programări & recepție rapidă": "Запись и быстрый приём",
    "Devize și comenzi de piese": "Сметы и заказ запчастей",
    "Istoric complet pe vehicul": "Полная история автомобиля",
    "În curând": "Скоро",
    "Facturare, e-Factura și rapoarte fiscale într-un sistem care închide luna fără nopți pierdute.": "Счета, e-Factura и налоговая отчётность в системе, которая закрывает месяц без бессонных ночей.",
    "Facturare & e-Factura": "Счета и e-Factura",
    "Registre și jurnale automate": "Автоматические регистры и журналы",
    "Rapoarte fiscale la zi": "Актуальная налоговая отчётность",
    "Zafirok este construit modular: activezi doar funcțiile de care are nevoie afacerea ta și plătești separat pentru fiecare modul. Când adaugi un modul nou, acesta se conectează instant cu datele și procesele pe care le folosești deja.": "Zafirok устроен по модулям: вы включаете только нужные бизнесу функции и платите отдельно за каждый модуль. Новый модуль сразу подключается к данным и процессам, которые вы уже используете.",
    "Date sincronizate": "Синхронизированные данные",
    "Clientul din CRM e același din facturare. Fără copy-paste, fără versiuni diferite ale adevărului.": "Клиент в CRM — тот же, что и в счетах. Без копирования и без разных версий правды.",
    "Cloud & mobil": "Облако и мобильность",
    "Lucrezi din birou, din service sau de pe șantier. Datele te urmează pe orice dispozitiv.": "Работайте из офиса, из сервиса или со стройки. Данные доступны на любом устройстве.",
    "Securitate serioasă": "Надёжная безопасность",
    "Backup automat, acces pe roluri și criptare. Datele afacerii tale rămân doar ale tale.": "Автоматическое резервное копирование, доступ по ролям и шифрование. Данные вашего бизнеса принадлежат только вам.",
    "Implementare rapidă": "Быстрое внедрение",
    "Pornești în zile, nu în luni. Importăm datele existente și îți instruim echipa.": "Старт за дни, а не за месяцы. Мы переносим существующие данные и обучаем вашу команду.",
    "Cash flow, vânzări, costuri pe proiect — cifrele care contează, fără să aștepți sfârșitul lunii.": "Денежный поток, продажи, затраты по проектам — важные цифры без ожидания конца месяца.",
    "Suport care răspunde": "Поддержка, которая отвечает",
    "Oameni reali, care înțeleg afacerea ta, nu doar software-ul. În limba ta, când ai nevoie.": "Живые люди, которые понимают ваш бизнес, а не только программу. На вашем языке, когда нужно.",
    "companii active": "активных компаний",
    "uptime garantat": "гарантированная доступность",
    "documente procesate": "обработанных документов",
    "Acum, datorită CRM-ului pentru electricieni și renovări, pot să țin sub control lucrul echipei mele: pe cine plătesc, ce volum face fiecare zilnic și orele de muncă. Înainte țineam totul în minte și aveam un carnețel în care era mereu încurcătură. Trebuia să calculez constant, era greu să țin cont de detaliile mici și nu mai știam cât câștig cu adevărat de pe fiecare obiect. Acum înregistrez toate proiectele în CRM și este atât de ușor să țin evidența, chiar e o plăcere. La început lucram în soft de pe telefon, dar apoi am trecut pe tabletă — îmi place să văd cifrele mai mari. Recomand: este mai simplu decât să ții calculele pe foaie și îți ia mai puțin timp decât să notezi în caiet.": "Теперь благодаря CRM для электриков и ремонта я держу работу своей команды под контролем: кому я плачу, какой объём каждый делает за день и сколько часов работает. Раньше я держал всё в голове и вёл блокнот, в котором вечно была путаница. Приходилось постоянно считать, было трудно учитывать мелочи, и я уже не понимал, сколько на самом деле зарабатываю на каждом объекте. Теперь я вношу все проекты в CRM, и вести учёт так легко, что это даже в удовольствие. Сначала я работал в программе с телефона, а потом перешёл на планшет — мне нравится видеть цифры крупнее. Рекомендую: это проще, чем считать на листке, и занимает меньше времени, чем записывать в тетрадь.",
    "Electricitate și renovări": "Электромонтаж и ремонт",
    "Căutam un CRM pentru service auto și, când am văzut publicitatea Zafirok, mi-a plăcut ce am văzut. Am scris un simplu comentariu că sunt interesată și nu credeam că o să revină cineva. Dar echipa a fost foarte receptivă atât la început, cât și ulterior. Le-am sugerat câteva îmbunătățiri și le-au implementat foarte rapid. Este un sistem digital modern pentru service auto.": "Я искала CRM для автосервиса и, увидев рекламу Zafirok, мне понравилось то, что я увидела. Я оставила простой комментарий, что мне интересно, и не думала, что кто-то ответит. Но команда была очень отзывчивой и в начале, и потом. Я предложила несколько улучшений, и их очень быстро внедрили. Это современная цифровая система для автосервиса.",
    "Un prieten care folosește deja Zafirok drept CRM pentru service-ul lui auto ne-a recomandat să ne înregistrăm. După doar câteva minute de utilizare, am înțeles că este ceea ce avem nevoie. Având câteva filiale, s-a dovedit a fi cea mai bună soluție. Este ușor de folosit, iar totul este gândit exact pentru nevoile pe care le avem într-un service auto.": "Друг, который уже использует Zafirok как CRM для своего автосервиса, посоветовал нам зарегистрироваться. Уже через несколько минут работы мы поняли, что это то, что нам нужно. У нас несколько филиалов, и это оказалось лучшим решением. Система простая в использовании, и всё продумано именно под задачи автосервиса.",
    "CRM-ul gestionează relația cu clientul. ERP-ul organizează resursele și operațiunile companiei. Zafirok le conectează prin module independente, pe care le activezi în funcție de nevoile și etapa afacerii tale.": "CRM управляет отношениями с клиентами. ERP организует ресурсы и операции компании. Zafirok связывает их через независимые модули, которые вы включаете в зависимости от задач и этапа развития бизнеса.",
    "Nu adaptăm afacerea la un software generic. Construim fluxurile în jurul modului în care lucrează fiecare nișă.": "Мы не подгоняем бизнес под типовую программу. Мы строим процессы вокруг того, как работает каждая ниша.",
    "Centralizează clienții, vânzările, comunicarea și istoricul fiecărei relații.": "Объединяет клиентов, продажи, коммуникацию и историю каждого сотрудничества.",
    "Coordonează operațiunile, costurile, stocurile, echipele și fluxurile financiare.": "Координирует операции, затраты, запасы, команды и финансовые потоки.",
    "Pontaj": "Табель",
    "Devize": "Сметы",
    "Facturare": "Счета",
    "Rapoarte": "Отчёты",
    "Programează un demo de 30 de minute. Îți arătăm ecosistemul pe datele tale, nu pe slide-uri.": "Запишитесь на 30-минутное демо. Мы покажем экосистему на ваших данных, а не на слайдах.",
    "Demo gratuit · Fără obligații · Răspundem în aceeași zi": "Бесплатное демо · Без обязательств · Ответим в тот же день",
    "Ecosistem de sisteme software pentru afaceri: CRM, service auto, contabilitate, construcții și fabrici. Un singur partener, toată afacerea acoperită.": "Экосистема программ для бизнеса: CRM, автосервис, бухгалтерия, строительство и производство. Один партнёр — весь бизнес под контролем.",
    "© 2026 Zafirok. Toate drepturile rezervate.": "© 2026 Zafirok. Все права защищены.",
    "Ce date colectăm și de ce": "Какие данные мы собираем и зачем",
    "Această pagină se referă la site-ul de prezentare zafirok.com. Aplicațiile Zafirok au fiecare propria politică, fiindcă acolo datele sunt ale clienților noștri, nu ale noastre.": "Эта страница относится к презентационному сайту zafirok.com. У каждого приложения Zafirok своя политика, потому что данные в них принадлежат нашим клиентам, а не нам.",
    "Ultima actualizare:": "Последнее обновление:",
    "19 august 2026": "19 августа 2026 г.",
    "Cine răspunde pentru datele tale": "Кто отвечает за ваши данные",
    "Operatorul este": "Оператором данных является",
    ", IDNO": ", IDNO",
    ", cu sediul în str. Calea Ieșilor 16, nr. 3, ap. 8V, MD-2069, Chișinău, Republica Moldova.": ", юридический адрес: str. Calea Ieșilor 16, nr. 3, ap. 8V, MD-2069, Кишинёв, Республика Молдова.",
    "este marca sub care oferim aplicațiile descrise pe acest site.": "— это бренд, под которым мы предлагаем приложения, описанные на этом сайте.",
    "Plățile pentru abonamente sunt facturate de": "Счета за подписки выставляет",
    ", 7901 4th St N, STE 300, St. Petersburg, FL 33702, Statele Unite, care prelucrează în acest scop numele, adresa de email și datele de facturare. Pentru orice altceva legat de datele tale, operatorul rămâne CreativMaro SRL.": ", 7901 4th St N, STE 300, St. Petersburg, FL 33702, США, которая для этой цели обрабатывает имя, адрес электронной почты и платёжные данные. По всем остальным вопросам, связанным с вашими данными, оператором остаётся CreativMaro SRL.",
    "Pentru orice întrebare privind datele tale sau pentru exercitarea drepturilor de mai jos, scrie la": "По любым вопросам о ваших данных или для осуществления перечисленных ниже прав пишите на",
    ". Răspundem în cel mult o lună de la primirea cererii.": ". Мы отвечаем не позднее чем через месяц после получения запроса.",
    "Prelucrăm datele conform": "Мы обрабатываем данные в соответствии с",
    "Legii nr. 195/2024 privind protecția datelor cu caracter personal": "Законом № 195/2024 о защите персональных данных",
    ", aplicabilă din 23 august 2026, iar pentru vizitatorii din Spațiul Economic European și conform Regulamentului (UE) 2016/679.": ", применяемым с 23 августа 2026 г., а для посетителей из Европейской экономической зоны — также с Регламентом (ЕС) 2016/679.",
    "Ce colectăm, în ce scop și pe ce temei": "Что мы собираем, с какой целью и на каком основании",
    "Pe site-ul de prezentare nu ai cont și nu îți cerem date pentru a naviga. Colectăm strict următoarele:": "На презентационном сайте у вас нет учётной записи, и мы не запрашиваем данные для просмотра. Мы собираем строго следующее:",
    "Date": "Данные",
    "Scop": "Цель",
    "Temei juridic": "Правовое основание",
    "Păstrare": "Срок хранения",
    "Adresa IP, tipul browserului, pagina vizitată": "IP-адрес, тип браузера, посещённая страница",
    "Funcționarea site-ului, securitate, prevenirea abuzurilor": "Работа сайта, безопасность, предотвращение злоупотреблений",
    "Interes legitim,": "Законный интерес,",
    "art. 6 alin. (1) lit. f)": "ст. 6 ч. (1) п. f)",
    "Maximum 90 de zile în jurnalele tehnice": "Не более 90 дней в технических журналах",
    "Preferința de limbă": "Выбранный язык",
    "Afișarea site-ului în limba aleasă": "Отображение сайта на выбранном языке",
    "Strict necesar pentru serviciul cerut": "Строго необходимо для запрошенной услуги",
    "Până la ștergerea din browser": "До удаления из браузера",
    "Statistici agregate de utilizare": "Обобщённая статистика использования",
    "Înțelegerea modului în care e folosit site-ul": "Понимание того, как используется сайт",
    "Consimțământ,": "Согласие,",
    "art. 6 alin. (1) lit. a)": "ст. 6 ч. (1) п. a)",
    "Doar dacă accepți, maximum 14 luni": "Только с вашего согласия, не более 14 месяцев",
    "Identificatori publicitari Meta": "Рекламные идентификаторы Meta",
    "Măsurarea campaniilor de promovare": "Оценка рекламных кампаний",
    "Doar dacă accepți, conform politicii Meta": "Только с вашего согласия, согласно политике Meta",
    "Numele și adresa de email, dacă ne scrii": "Имя и адрес электронной почты, если вы нам пишете",
    "Răspunsul la mesajul tău": "Ответ на ваше сообщение",
    "Măsuri precontractuale,": "Преддоговорные меры,",
    "art. 6 alin. (1) lit. b)": "ст. 6 ч. (1) п. b)",
    "24 de luni de la ultima corespondență": "24 месяца с момента последней переписки",
    "Statisticile și identificatorii publicitari nu pornesc înainte să alegi. Dacă refuzi, site-ul funcționează identic.": "Статистика и рекламные идентификаторы не запускаются, пока вы не сделаете выбор. Если вы откажетесь, сайт работает точно так же.",
    "Cui ajung datele": "Кому передаются данные",
    "Nu vindem date și nu le facem publice. Le pot prelucra doar furnizorii de care avem nevoie ca să ținem site-ul în funcțiune:": "Мы не продаём данные и не публикуем их. Обрабатывать их могут только поставщики, необходимые для работы сайта:",
    ", Statele Unite, găzduire și jurnale de acces.": ", США, хостинг и журналы доступа.",
    ", Statele Unite, măsurarea campaniilor, numai cu acordul tău.": ", США, оценка кампаний, только с вашего согласия.",
    "Putem transmite date și autorităților, dar numai când o obligație legală ne impune asta și numai în limita cerută.": "Мы можем передавать данные и государственным органам, но только если этого требует закон и только в необходимом объёме.",
    "Transferuri în afara Republicii Moldova": "Передача данных за пределы Республики Молдова",
    "Furnizorii de mai sus prelucrează date în Statele Unite. Transferul se face în baza": "Перечисленные поставщики обрабатывают данные в США. Передача осуществляется на основании",
    "clauzelor contractuale standard": "стандартных договорных положений",
    ", mecanism admis fără autorizare prealabilă de": ", — механизма, допускаемого без предварительного разрешения согласно",
    "art. 46 alin. (2) lit. c)": "ст. 46 ч. (2) п. c)",
    "din Legea nr. 195/2024, iar pentru identificatorii publicitari și în baza consimțământului tău explicit,": "Закона № 195/2024, а для рекламных идентификаторов — также на основании вашего явного согласия,",
    "art. 49 alin. (1) lit. a)": "ст. 49 ч. (1) п. a)",
    "Documentele și fișierele încărcate în aplicațiile noastre sunt stocate pe servere din": "Документы и файлы, загруженные в наши приложения, хранятся на серверах во",
    "Franța": "Франции",
    ". Fiind în Spațiul Economic European, aceste transferuri nu necesită nicio formalitate suplimentară, conform": ". Поскольку это Европейская экономическая зона, такая передача не требует дополнительных формальностей согласно",
    "art. 44 alin. (2)": "ст. 44 ч. (2)",
    "Poți cere oricând o copie a garanțiilor aplicate, scriindu-ne la adresa de mai sus.": "Вы можете в любой момент запросить копию применяемых гарантий, написав нам по адресу выше.",
    "Drepturile tale": "Ваши права",
    "Ai, în legătură cu datele tale, următoarele drepturi:": "В отношении ваших данных у вас есть следующие права:",
    "Acces": "Доступ",
    ", să afli ce date avem despre tine, art. 15.": ", чтобы узнать, какие данные о вас у нас есть, ст. 15.",
    "Rectificare": "Исправление",
    ", să corectăm ce e greșit, art. 16.": ", чтобы мы исправили неверные данные, ст. 16.",
    "Ștergere": "Удаление",
    ", să eliminăm datele, art. 17.": ", чтобы мы удалили данные, ст. 17.",
    "Restricționare": "Ограничение",
    ", să oprim temporar prelucrarea, art. 18.": ", чтобы мы временно прекратили обработку, ст. 18.",
    "Portabilitate": "Переносимость",
    ", să primești datele într-un format citibil automat, art. 20.": ", чтобы получить данные в машиночитаемом формате, ст. 20.",
    "Opoziție": "Возражение",
    ", să te opui prelucrării întemeiate pe interes legitim, art. 21.": ", чтобы возразить против обработки на основании законного интереса, ст. 21.",
    "Retragerea consimțământului": "Отзыв согласия",
    ", oricând și la fel de simplu cum l-ai dat, art. 7 alin. (3). Pentru cookie-uri, folosește „Setări cookie-uri\" din piciorul paginii.": ", в любой момент и так же просто, как вы его дали, ст. 7 ч. (3). Для cookie используйте «Настройки cookie» внизу страницы.",
    "Nu luăm decizii automatizate cu efecte juridice asupra ta și nu facem profilare pe site-ul de prezentare.": "Мы не принимаем автоматизированных решений с правовыми последствиями для вас и не проводим профилирование на презентационном сайте.",
    "Dacă nu ești mulțumit de răspunsul nostru": "Если вас не устраивает наш ответ",
    "Scrie-ne întâi nouă, de obicei se rezolvă mai repede. Dacă nu ești mulțumit, ai dreptul să depui plângere la": "Сначала напишите нам — обычно так решается быстрее. Если вас не устроит ответ, вы вправе подать жалобу в",
    "Centrul Național pentru Protecția Datelor cu Caracter Personal": "Национальный центр по защите персональных данных",
    ", str. Serghei Lazo 48, Chișinău, MD-2004, sau prin": ", str. Serghei Lazo 48, Кишинёв, MD-2004, или через",
    ". Te poți adresa și instanței de judecată.": ". Вы также можете обратиться в суд.",
    "Modificări": "Изменения",
    "Când schimbăm ceva important, actualizăm data de sus și, dacă modificarea te afectează direct, îți cerem din nou alegerea privind cookie-urile. Versiunile anterioare sunt disponibile la cerere.": "Когда мы меняем что-то важное, мы обновляем дату вверху и, если изменение касается вас напрямую, снова спрашиваем ваш выбор в отношении cookie. Предыдущие версии доступны по запросу.",
    "Ce se salvează în browserul tău": "Что сохраняется в вашем браузере",
    "Site-ul funcționează complet și dacă refuzi tot ce nu e strict necesar. Nu ascundem opțiunea de refuz și nu îți cerem alegerea din nou la fiecare vizită.": "Сайт полностью работает, даже если вы откажетесь от всего, что не является строго необходимым. Мы не прячем возможность отказа и не спрашиваем ваш выбор при каждом визите.",
    "Alegerea ta, oricând": "Ваш выбор — в любой момент",
    "Îți poți schimba opțiunile în orice moment, fără să ne scrii și fără să îți creezi cont. Retragerea are efect imediat pentru vizitele următoare.": "Вы можете изменить настройки в любой момент, не обращаясь к нам и не создавая учётную запись. Отзыв согласия сразу действует для следующих посещений.",
    "Fără ele site-ul nu poate funcționa, așa că nu îți cerem acordul pentru ele. Nu te urmăresc și nu ajung la nimeni altcineva.": "Без них сайт не может работать, поэтому мы не спрашиваем на них согласия. Они не отслеживают вас и никому не передаются.",
    "Ce salvăm": "Что мы сохраняем",
    "La ce folosește": "Для чего",
    "Cât stă": "Как долго хранится",
    "limbă": "язык",
    "Ține minte dacă citești în română, rusă sau engleză": "Запоминает, читаете ли вы на румынском, русском или английском",
    "Până îl ștergi": "Пока вы его не удалите",
    "Reține chiar alegerea ta privind cookie-urile, ca să nu te întrebăm iar": "Хранит сам ваш выбор в отношении cookie, чтобы не спрашивать снова",
    "12 luni": "12 месяцев",
    "Ne arată ce pagini sunt citite și unde oamenii se opresc, în formă agregată. Pornesc numai dacă le accepți.": "Они показывают в обобщённом виде, какие страницы читают и где люди останавливаются. Запускаются только с вашего согласия.",
    "În acest moment nu rulăm niciun instrument de statistică pe site-ul de prezentare. Dacă adăugăm unul, actualizăm această pagină și îți cerem din nou alegerea, înainte ca instrumentul să pornească.": "Сейчас на презентационном сайте не работает ни один инструмент статистики. Если мы его добавим, мы обновим эту страницу и снова спросим ваш выбор до того, как инструмент запустится.",
    "Pornesc numai cu acordul tău explicit și pot fi oprite oricând.": "Запускаются только с вашего явного согласия и могут быть отключены в любой момент.",
    "Furnizor": "Поставщик",
    "Ce face": "Что делает",
    "Unde ajung datele": "Куда передаются данные",
    "Măsoară câți vizitatori vin din campaniile noastre de promovare și ne ajută să nu arătăm reclame celor care ne-au contactat deja": "Измеряет, сколько посетителей приходит из наших рекламных кампаний, и помогает не показывать рекламу тем, кто уже с нами связался",
    "Meta Platforms Inc., Statele Unite": "Meta Platforms Inc., США",
    "Pixelul transmite adresa IP și identificatori de dispozitiv către Meta, în Statele Unite. De aceea îl tratăm ca transfer internațional și îl pornim doar pe baza consimțământului explicit, conform": "Пиксель передаёт IP-адрес и идентификаторы устройства компании Meta в США. Поэтому мы рассматриваем это как международную передачу данных и запускаем его только на основании явного согласия, согласно",
    "din Legea nr. 195/2024. Detalii în": "Закона № 195/2024. Подробнее — в",
    "Cum le ștergi din browser": "Как удалить их из браузера",
    "Pe lângă panoul nostru de setări, poți șterge sau bloca tot ce salvează site-urile direct din browser, de obicei din secțiunea de confidențialitate. Reține că blocarea totală afectează multe site-uri, nu doar pe al nostru.": "Помимо нашей панели настроек, вы можете удалить или заблокировать всё, что сохраняют сайты, прямо в браузере — обычно в разделе конфиденциальности. Учтите, что полная блокировка влияет на многие сайты, а не только на наш.",
    // Cuvintele rămase în engleză și în versiunea română, dar nu și în rusă.
    "uptime": "доступность",
    "Cloud": "Облако",
    "Mobile": "Мобильность",
    "Email": "Эл. почта",
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ro");

  useEffect(() => {
    const saved = localStorage.getItem("zafirok-language") as Language | null;
    const browser = navigator.language.toLowerCase();
    setLanguageState(saved && ["ro", "ru", "en"].includes(saved) ? saved : browser.startsWith("ru") ? "ru" : browser.startsWith("en") ? "en" : "ro");
  }, []);

  useEffect(() => { document.documentElement.lang = language; }, [language]);

  useEffect(() => {
    const translatePage = () => {
      const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
      let node: Node | null;
      while ((node = walker.nextNode())) {
        const textNode = node as Text;
        const raw = originalTexts.get(textNode) ?? textNode.data;
        originalTexts.set(textNode, raw);
        const trimmed = raw.trim();
        if (!trimmed) continue;
        const translated = language === "ro" ? trimmed : translations[language][trimmed];
        if (translated) textNode.data = raw.replace(trimmed, translated);
      }
    };
    translatePage();
    const observer = new MutationObserver(translatePage);
    observer.observe(document.body, { childList: true, subtree: true });
    return () => observer.disconnect();
  }, [language]);

  const setLanguage = (next: Language) => {
    localStorage.setItem("zafirok-language", next);
    setLanguageState(next);
  };

  return <LanguageContext.Provider value={{ language, setLanguage }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() { return useContext(LanguageContext); }
